# Numpy vectorization

In [4]:
import numpy as np

import IPython
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Read from files

In [40]:
import tempfile
from io import StringIO

fname = tempfile.mkstemp()[1]
print(fname)

arr = np.array([1,2,3,4,5])

# save
np.save(fname, x)

# load
np.load(fname + '.npy')

num_text = u"0 1\n2 3"
print(f"num_text: \n{num_text}")

c = StringIO(num_text)

np.loadtxt(c)

/tmp/tmpscc_p4ds


array([1, 2, 3, 4, 5])

num_text: 
0 1
2 3


array([[0., 1.],
       [2., 3.]])

## Vectors Linear Algebra

* norm
* transpose
* dot product 


In [97]:
np.zeros((2,2))
np.ones((3,2))

np.identity(3)

# extract the diagonal A must be 2D array
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A
np.diag(A)

# build a diagonal matrix. input must be 1d array
A = np.array([1, 2, 3])

np.diag(A)

print("Create empyt array. Useful for stacking")
e = np.empty((2,3), dtype=np.int)
e.shape
e.dtype

array([[0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([1, 5, 9])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Create empyt array. Useful for stacking


(2, 3)

dtype('int64')

In [94]:
v1 = np.array([3.0,4.0])
np.linalg.norm(v1)


e1 = np.array([1.0,0.0])
e2 = np.array([0.0,4.0])

np.dot(e1,e2)

5.0

0.0

In [90]:
I = np.array([[1.0,0.0],[0.0,1.0]])
A = np.array([[1.0,0.5],[2.0,2.0]])
I
A

# elemnt wise mutliplication
A*I
np.multiply(A,I)


print("matrix multiplication")
# matrix multiplication
np.matmul(A,I)

# Transpose
A.T

array([[1., 0.],
       [0., 1.]])

array([[1. , 0.5],
       [2. , 2. ]])

array([[1., 0.],
       [0., 2.]])

array([[1., 0.],
       [0., 2.]])

matrix multiplication


array([[1. , 0.5],
       [2. , 2. ]])

array([[1. , 2. ],
       [0.5, 2. ]])

## Vectorization operations

In [99]:
a = np.array([1,2,3,4])
a

a.reshape((2,2))

a.reshape((2,2,1)).shape


e1 = np.array([1.0,0.0])
e2 = np.array([0.0,4.0])

np.vstack((e1,e2))

np.hstack((e1,e2))

A = np.array([[1,2], [3,4]])
A.flatten()

array([1, 2, 3, 4])

array([[1, 2],
       [3, 4]])

(2, 2, 1)

array([[1., 0.],
       [0., 4.]])

array([1., 0., 0., 4.])

array([1, 2, 3, 4])

In [26]:
arr = np.array([[1,2,3,4,5],[0,0,0,1,2]])

print("Last element of all rows")
arr[:,-1]

print("Slices examples")

## from n to last one
arr = np.array([1,2,3,4,5])
arr[2:]

# All elements except last one 
arr[:-1]
arr[:-2]

Last element of all rows


array([5, 2])

Slices examples


array([3, 4, 5])

array([1, 2, 3, 4])

array([1, 2, 3])

In [48]:
# reverse 
arr
arr[::-1]

# linearspace
np.linspace(0.0,5.0,4)

array([1, 2, 3, 4, 5])

array([5, 4, 3, 2, 1])

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [113]:
v = np.array([0.1,-0.1,0.0,0.2])
v

rtol = 0.20 # relative tolerance 30%
atol = 0.3 # absolute tolerance
np.allclose(v, np.zeros(v.shape), rtol, atol)

array([ 0.1, -0.1,  0. ,  0.2])

True

In [121]:
# eigen vecotrs and values

A = np.array([[-6,3],[4,5]])
A

# Av = lambda v
eigen_vals, eigen_vecs = np.linalg.eig(A)

lambda1 = eigen_vals[0]
lambda2 =  eigen_vals[1]

# eigenvecotr are the columns of the output matrix
e1 = eigen_vecs[:, 0]
e2 = eigen_vecs[:, 1]


# ok 
np.matmul(A,e1)
lambda1*e1

# ok
np.matmul(A,e2)
lambda2*e2

# fail
np.matmul(A,e1)
lambda2*e1

array([[-6,  3],
       [ 4,  5]])

array([ 6.64078309, -2.21359436])

array([ 6.64078309, -2.21359436])

array([-1.45521375, -5.820855  ])

array([-1.45521375, -5.820855  ])

array([ 6.64078309, -2.21359436])

array([-5.69209979,  1.8973666 ])

## Functional programming

In [28]:
arr = np.array([1, 2, 3, 4, 5])
squarer = lambda t: t ** 2

# easy to read
np.array([x*x for x in arr  ])

vfunc = np.vectorize(squarer)
vfunc(arr)

array([ 1,  4,  9, 16, 25])

array([ 1,  4,  9, 16, 25])

In [76]:
A = np.array([[3,2,1], [4,8,6], [7,5,9]])
A

# sort all columns
np.apply_along_axis(sorted, 0, A)

# sort all rows
np.apply_along_axis(sorted, 1, A)

array([[3, 2, 1],
       [4, 8, 6],
       [7, 5, 9]])

array([[3, 2, 1],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3],
       [4, 6, 8],
       [5, 7, 9]])

## Random numbers

In [49]:
np.random.seed(3)

arr = np.array([1,2,3,4,5])

# sample with repetition
x = np.random.choice(arr, size=7)
x

# uniform
s = np.random.uniform(-1,1,5)
s

# normal distribution
mu, sigma = 0, 1.0 # mean and standard deviation
s = np.random.normal(mu, sigma, 100)

array([3, 1, 2, 4, 1, 1, 1])

array([ 0.13862265, -0.12587612, -0.96250398, -0.91873853, -0.50422341])

In [60]:
# random permutation [0-10]
np.random.permutation(10)

array([9, 8, 7, 2, 6, 0, 1, 4, 5, 3])

## Statisics

In [72]:
A = np.array([[1, 2], [3, 4]])
print(A)


# global mean
np.mean(A)

# column mean
np.mean(A,axis=0)

# row mean
np.mean(A,axis=1)

A = np.array([[20, 15, 37], [47, 13, np.nan]])  

# ignore nan
np.nanmean(A)
np.mean(A)

[[1 2]
 [3 4]]


2.5

array([2., 3.])

array([1.5, 3.5])

26.4

nan

In [70]:
A = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

q =  50 # percentile 0-100 , 50 is the median
np.percentile(A, q, axis=0)
np.median(A,axis=0)


# Raneg funcrion return (max - min)
A = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
A

np.ptp(A, axis = 0) 

array([50., 40., 60.])

array([50., 40., 60.])

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

array([6, 3, 6])